### ISSUE TITLE
Problem while training

### ISSUE THREAD

**Issue by sarthaksnh5** [joeVenner/FaceRecognition-GUI-APP#1]
clf.train(faces, ids)
cv2.error: OpenCV(4.2.0) /io/opencv_contrib/modules/face/src/lbph_faces.cpp:362: error: (-210:Unsupported format or combination of formats) Empty training data was given. You'll need more than one sample to learn a model. in function 'train'

**Comment by joeVenner** [comment]
Hi 
first are you on Linux or windows !
then Please check the **data folder** if the script captured enough pics

**Comment by joeVenner** [comment]
download the new **create_classifier.py** file 
i just fixed the error
